version: 1.2.6

artifacts:
  - path: hello-appveyor.zip
    name: hello-appveyor
  - path: '*.log'
    name: logs

branches:
  only:
    - master

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - rem add python 3.9 to path
  - set PATH=C:\Python39-x64;C:\Python39-x64\Scripts;%PATH%
  - rem add qt msvc2017 to path
  - set PATH=C:\Qt\5.14.2\msvc2017_64\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - qmake > build_qmake.log 2>&1
  - jom release > build_jom.log 2>&1
  - jom clean > nul 2>&1
  - windeployqt release\hello-appveyor.exe > deploy.log 2>&1
  - 7z a hello-appveyor.zip release > zip.log 2>&1

test_script:
  - rem appveyor AddTest -Name "Test A" -Framework NUnit -Filename a.exe -Outcome Passed -Duration 1000
  - cd tests
  - qmake >> ..\build_tests.log 2>&1
  - jom release >> ..\build_tests.log 2>&1
  - cd ..
  - powershell tests.ps

deploy:
  description: 'hello-appveyor'
  provider: GitHub
  auth_token:
    secure: gcYWBlGRr48R9W3Snz+xXmLh1TIT/wYLnoYgdaCRlKiWA4SyZkNC3b+GZdIiyCra
  on:
    branch: master